# Generated by Django 2.1.1 on 2019-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20190520_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='owner',
            field=models.CharField(max_length=250),
        ),
    ]
